config/routes.rb
Rails.application.routes.draw do
  root 'nodes#index'


  resources :nodes
  get :test_connection, to: 'nodes#test_connection'
  get :test , to: 'nodes#test_connection'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  validates :NodeName, presence: true, uniqueness: true

  def self.update_or_create_by_node_info(node_data)
    node = find_or_initialize_by(NodeName: node_data[:NodeName])
    node.update(node_data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :load_nodes, only: [:index, :show]

  def index
    @nodes = Node.all
  end

  def show
    @node = Node.find(params[:id])
  end

  private

  def load_nodes
    @nodes = Node.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CarcStatus
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'skeleton'
  %body
    = yield

app/views/nodes/index.html.haml
!!!
%html
  %head
    %title Node Information
    = stylesheet_link_tag 'skeleton'
    = csrf_meta_tags

  %body
    %h1 Node Information

    %table.table.table-striped
      %thead
        %tr
          %th Node Name
          %th Cores Per Socket
          %th CPU Alloc
          %th CPU Load
          %th Real Memory
          %th Alloc Mem
          %th Free Mem
          %th Sockets
          %th Boards
          %th State
          %th Threads Per Core
          %th Partitions
          %th Current Watts
          %th Average Watts

      %tbody
        - @nodes.each do |node|
          %tr
            %td= node.NodeName
            %td= node.CoresPerSocket
            %td= node.CPUAlloc
            %td= node.CPULoad
            %td= node.RealMemory
            %td= node.AllocMem
            %td= node.FreeMem
            %td= node.Sockets
            %td= node.Boards
            %td= node.State
            %td= node.ThreadsPerCore
            %td= node.Partitions
            %td= node.CurrentWatts
            %td= node.AveWatts

    %h2
      = link_to 'Test', test_path

app/views/nodes/test_connection.html.haml
%h1 Test Connection
%p This is the test connection page.

%h2 Hostname
%p= @hostname || 'Failed to fetch hostname'

%h2 System Date
%p= @date || 'Failed to fetch system date'